services:
  kibana:
    container_name: kibana
    image: docker.apnictraining.net/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - custom_mgmt
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.apnictraining.net/elasticsearch:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      - custom_mgmt
  salt:
    image: docker.apnictraining.net/ubuntu-salt:20.04
    container_name: salt
    restart: unless-stopped
    hostname: salt
    volumes:
      - /srv/salt:/srv/salt
      - /etc/salt:/etc/salt
    networks:
      - custom_mgmt
  srv1:
    image: docker.apnictraining.net/ubuntu-apnic-ssh:20.04
    restart: unless-stopped
    hostname: srv1
    container_name: srv1
  srv2:
    image: docker.apnictraining.net/ubuntu-apnic-ssh:20.04
    restart: unless-stopped
    hostname: srv2
    container_name: srv2
  srv3:
    image: docker.apnictraining.net/ubuntu-apnic-ssh:20.04
    restart: unless-stopped
    hostname: srv2
    container_name: srv3

networks:
  custom_mgmt:
    name: custom_mgmt
    external: true
